<project xmlns="http://maven.apache.org/POM/4.0.0"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="
          http://maven.apache.org/POM/4.0.0
          http://maven.apache.org/xsd/maven-4.0.0.xsd">
   <modelVersion>4.0.0</modelVersion>

   <groupId>com.heapik.slot</groupId>
   <artifactId>commons</artifactId>
   <version>${revision}</version>
   <packaging>pom</packaging>

   <modules>
       <module>commons-event</module>
       <module>commons-api</module>
   </modules>

   <distributionManagement>
       <repository>
           <id>github</id>
           <name>GitHub Packages</name>
           <url>https://maven.pkg.github.com/nikolamanojlovic/slot-commons</url>
       </repository>
   </distributionManagement>

   <properties>
       <revision>1.0.7</revision>
       <maven.compiler.source>21</maven.compiler.source>
       <maven.compiler.target>21</maven.compiler.target>
       <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
   </properties>

   <build>
       <plugins>
           <plugin>
               <groupId>org.codehaus.mojo</groupId>
               <artifactId>flatten-maven-plugin</artifactId>
               <version>1.6.0</version>
               <configuration>
                   <updatePomFile>true</updatePomFile>
               </configuration>
               <executions>
                   <execution>
                       <id>flatten</id>
                       <phase>process-resources</phase>
                       <goals><goal>flatten</goal></goals>
                   </execution>
               </executions>
           </plugin>
       </plugins>
   </build>
</project>
